-- MySQL Script generated by MySQL Workbench
-- Thu Jun  8 19:32:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `ID_Categoria` INT NOT NULL,
  `NombreCategoria` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `CodigoProducto` VARCHAR(45) NOT NULL,
  `NombreProducto` VARCHAR(45) NULL,
  `DetalleProducto` VARCHAR(45) NULL,
  `PrecioUnitario` VARCHAR(45) NULL,
  `ID_Categoria` INT NULL,
  PRIMARY KEY (`CodigoProducto`),
  INDEX `ID_Categoria_idx` (`ID_Categoria` ASC) VISIBLE,
  CONSTRAINT `ID_Categoria`
    FOREIGN KEY (`ID_Categoria`)
    REFERENCES `mydb`.`Categoria` (`ID_Categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `ID_Usuario` INT NOT NULL,
  `NombreUsuario` VARCHAR(45) NULL,
  `ContraseñaUsuario` VARCHAR(45) NULL,
  `ID_RolUsuario` INT NULL,
  PRIMARY KEY (`ID_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recibo` (
  `ID_Recibo` INT NOT NULL,
  `ID_Factura` INT NULL,
  `Archivo` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Recibo`),
  INDEX `ID_Factura_idx` (`ID_Factura` ASC) VISIBLE,
  CONSTRAINT `ID_Factura`
    FOREIGN KEY (`ID_Factura`)
    REFERENCES `mydb`.`Factura` (`ID_Factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MetodoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MetodoPago` (
  `ID_MetodoPago` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Recargo` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_MetodoPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `ID_Factura` INT NOT NULL,
  `ID_Recibo` INT NULL,
  `MetodoPago` INT NULL,
  `FechaRealizacion` DATETIME NULL,
  `TotalCuenta` INT NULL,
  PRIMARY KEY (`ID_Factura`),
  INDEX `ID_Recibo_idx` (`ID_Recibo` ASC) VISIBLE,
  INDEX `ID_MetodoPago_idx` (`MetodoPago` ASC) VISIBLE,
  CONSTRAINT `ID_Recibo`
    FOREIGN KEY (`ID_Recibo`)
    REFERENCES `mydb`.`Recibo` (`ID_Recibo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_MetodoPago`
    FOREIGN KEY (`MetodoPago`)
    REFERENCES `mydb`.`MetodoPago` (`ID_MetodoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stock` (
  `ID_ControlStock` INT NOT NULL,
  `CodigoProducto` VARCHAR(45) NULL,
  `ID_EstadoReposicion` INT NULL,
  PRIMARY KEY (`ID_ControlStock`),
  INDEX `CodigoProducto_idx` (`CodigoProducto` ASC) VISIBLE,
  CONSTRAINT `CodigoProducto`
    FOREIGN KEY (`CodigoProducto`)
    REFERENCES `mydb`.`Aplicacion` (`CodigoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aplicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aplicacion` (
  `CodigoProducto` VARCHAR(45) NULL,
  `ID_Usuario` INT NULL,
  `ID_ControlStock` INT NULL,
  `ID_Factura` INT NULL,
  INDEX `CodigoProducto_idx` (`CodigoProducto` ASC) VISIBLE,
  INDEX `ID_Usuario_idx` (`ID_Usuario` ASC) VISIBLE,
  INDEX `ID_Factura_idx` (`ID_Factura` ASC) VISIBLE,
  INDEX `ID_ControlStock_idx` (`ID_ControlStock` ASC) VISIBLE,
  CONSTRAINT `CodigoProducto`
    FOREIGN KEY (`CodigoProducto`)
    REFERENCES `mydb`.`Producto` (`CodigoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Usuario`
    FOREIGN KEY (`ID_Usuario`)
    REFERENCES `mydb`.`Usuario` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Factura`
    FOREIGN KEY (`ID_Factura`)
    REFERENCES `mydb`.`Factura` (`ID_Factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_ControlStock`
    FOREIGN KEY (`ID_ControlStock`)
    REFERENCES `mydb`.`Stock` (`ID_ControlStock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductosCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductosCompra` (
  `CodigoProducto` VARCHAR(45) NOT NULL,
  `ID_Factura` INT NOT NULL,
  `Precio` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`CodigoProducto`, `ID_Factura`),
  INDEX `ID_Factura_idx` (`ID_Factura` ASC) VISIBLE,
  CONSTRAINT `CodigoProducto`
    FOREIGN KEY (`CodigoProducto`)
    REFERENCES `mydb`.`Aplicacion` (`CodigoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Factura`
    FOREIGN KEY (`ID_Factura`)
    REFERENCES `mydb`.`Factura` (`ID_Factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
